"use client";

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { Sparkles, ArrowLeft, Bell, Clock } from 'lucide-react';
import api from '@/lib/axios';

export default function Notifications() {
  const [notifications, setNotifications] = useState([]);
  const [loading, setLoading] = useState(true);
  const router = useRouter();

  useEffect(() => {
    const fetchNotifications = async () => {
      try {
        const res = await api.get('/notifications');
        setNotifications(res.data.notifications);
        
        // Mark as read immediately
        if (res.data.notifications.some((n: any) => !n.is_read)) {
          await api.put('/notifications/read');
        }
      } catch (err: any) {
        if (err.response?.status === 401) router.push('/login');
      } finally {
        setLoading(false);
      }
    };
    fetchNotifications();
  }, [router]);

  return (
    <div className="min-h-screen px-4 py-8 sm:px-6 lg:px-8 max-w-3xl mx-auto">
      <nav className="flex justify-between items-center mb-8">
        <Link href="/posts" className="inline-flex items-center gap-2 text-indigo-400 hover:text-indigo-300 transition-colors">
          <ArrowLeft className="w-4 h-4" /> Back to Dashboard
        </Link>
        <Link href="/" className="text-2xl font-bold tracking-tighter flex items-center gap-2">
          <Sparkles className="text-indigo-400" />
          <span>Team<span className="text-indigo-400">Up</span></span>
        </Link>
      </nav>

      <div className="mb-8 flex items-center gap-3">
        <div className="w-12 h-12 rounded-full bg-indigo-500/20 flex items-center justify-center text-indigo-400">
          <Bell className="w-6 h-6" />
        </div>
        <div>
          <h1 className="text-3xl font-bold">Notifications</h1>
          <p className="text-gray-400">Updates on your applications generated by DB Triggers.</p>
        </div>
      </div>

      {loading ? (
        <div className="text-indigo-400">Loading notifications...</div>
      ) : notifications.length === 0 ? (
        <div className="text-center py-20 glass-panel">
          <Bell className="w-12 h-12 text-gray-600 mx-auto mb-4" />
          <h3 className="text-xl font-bold mb-2">All Caught Up!</h3>
          <p className="text-gray-400 mb-6">You don't have any notifications right now.</p>
        </div>
      ) : (
        <div className="space-y-4">
          {notifications.map((notif: any) => (
            <div key={notif.id} className={`glass-panel p-5 transition-colors ${notif.is_read ? 'opacity-70' : 'border-indigo-500/50'}`}>
              <div className="flex justify-between items-start mb-2">
                <span className="text-xs font-bold uppercase tracking-wider text-indigo-400">
                  {notif.type.replace('_', ' ')}
                </span>
                <span className="text-xs text-gray-500 flex items-center gap-1">
                  <Clock className="w-3 h-3" />
                  {new Date(notif.created_at).toLocaleString()}
                </span>
              </div>
              <p className="text-gray-200">{notif.message}</p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
